spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/revision
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.hbm2ddl.auto: create-drop
    generate-ddl: true
    show-sql: true

server:
  port: 8081
